name: "🚀 publish nuget"

on:
  push:
    branches:
      - main

jobs:
  release:
    name: publish nuget
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"
      - name: Build solution
        run: |
          cd nuget/Applogger
          dotnet build --configuration release
      - name: Test
        run: |
          cd nuget/Applogger
          dotnet test
      - name: Generate NuGet package
        run: |
          cd nuget/Applogger
          dotnet pack -c Release -o out --version-suffix v-$(date +%Y%m%d%H%M%S)
      - name: Push with dotnet
        run: |
          cd nuget/Applogger
          dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
